/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoArchitect.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.XTemplate',
        'Ext.grid.plugin.RowEditing',
        'Ext.layout.container.Border',
        'Ext.grid.Panel',
        'Ext.grid.column.Template',
        'Ext.grid.column.Date'
    ],

    id: 'mainView',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'mainPanel',
                    resizable: false,
                    layout: {
                        type: 'border'
                    },
                    collapsed: false,
                    manageHeight: false,
                    title: 'My Tasks',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            itemId: 'mainToolbar',
                            items: [
                                {
                                    xtype: 'label'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'addButton',
                                    icon: 'resources/images/add.png',
                                    text: 'Add Task'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            region: 'west',
                            split: true,
                            border: '2 2 2 2',
                            id: '',
                            itemId: 'gridPanel',
                            width: 150,
                            resizable: false,
                            bodyBorder: true,
                            forceFit: true,
                            store: 'Tasks',
                            columns: [
                                {
                                    xtype: 'templatecolumn',
                                    tpl: [
                                        '<span style="font-size: 1.1em; font-weight: bold">{title}</span>'
                                    ],
                                    text: 'Task',
                                    editor: {
                                        xtype: 'textfield',
                                        name: 'title'
                                    }
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'dueDate',
                                    text: 'Due Date',
                                    editor: {
                                        xtype: 'datefield'
                                    }
                                },
                                {
                                    xtype: 'templatecolumn',
                                    tpl: [
                                        '<table>',
                                        '    <tr>',
                                        '        <td style="padding-right: 8px">',
                                        '            <img src="resources/images/{priority}.png" title="{priority} Priority" />',
                                        '        </td>',
                                        '    	<td>',
                                        '            {priority}',
                                        '        </td>',
                                        '    </tr>',
                                        '</table>'
                                    ],
                                    text: 'Priority',
                                    editor: {
                                        xtype: 'combobox',
                                        name: 'priority',
                                        emptyText: 'Select Priority',
                                        editable: false,
                                        displayField: 'priority',
                                        store: 'Priorities',
                                        valueField: 'priority'
                                    }
                                }
                            ],
                            plugins: [
                                Ext.create('Ext.grid.plugin.RowEditing', {

                                })
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            split: true,
                            border: '2 2 2 2',
                            data: {
                                
                            },
                            itemId: 'detailsPanel',
                            tpl: [
                                '<tpl if="values.id">',
                                '    <h1>{title}</h1>',
                                '    <p>',
                                '        {description}',
                                '    </p>',
                                '</tpl>',
                                '',
                                '<tpl if="!values.id">',
                                '    <h1>Click task to view</h1>',
                                '</tpl>'
                            ],
                            resizable: false,
                            layout: {
                                type: 'fit'
                            },
                            bodyBorder: true,
                            bodyPadding: '10 10 10 10',
                            manageHeight: false,
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    hidden: true,
                                    itemId: 'detailsToolbar',
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'editButton',
                                            icon: 'resources/images/edit.png',
                                            text: 'Edit'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'removeButton',
                                            icon: 'resources/images/delete.png',
                                            text: 'Delete'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});