/*
 * File: app/model/Task.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DemoArchitect.model.Task', {
    extend: 'Ext.data.Model',
    alias: 'model.task',

    requires: [
        'DemoArchitect.DirectAPI',
        'Ext.data.Field',
        'Ext.data.proxy.Direct',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'title'
        },
        {
            name: 'description'
        },
        {
            name: 'dueDate',
            type: 'date'
        },
        {
            name: 'priority'
        }
    ],

    proxy: {
        type: 'direct',
        api: {
            create: 'ExtRemote.DXTask.create',
            read: 'ExtRemote.DXTask.read',
            update: 'ExtRemote.DXTask.update',
            destroy: 'ExtRemote.DXTask.destroy'
        },
        reader: {
            type: 'json',
            messageProperty: 'message',
            root: 'data'
        }
    }
});